#!/usr/bin/env python3
import judge
from time import process_time


def chinese_wall_parking(A):
    """finds the minimal number of car moves required to fulfill the law"""
    B = []  # was this car used in a cycle already?
    for a in A:
        B.append(False)
    moves = 0
    for i in range(0, len(A)):
        if A[i] == i or B[i]:
            # no need to move a car that's already in the right place
            # or to check a car that was already part of a cycle
            continue
        # the car at place i needs to be moved
        moves += 1
        B[i] = True  # mark that this car was part of a cycle
        next_car = A[i]
        # all cars in this cycle and need to be moved
        while next_car != i:
            moves += 1
            B[next_car] = True
            next_car = A[next_car]
        # one more move required to move the first car to the empty space
        moves += 1
    return [moves]


# A&D programming exercise number
exercise = 6
# inputs from the test files
inputs = judge.read_input(exercise)
# outputs generated by the algorithm
start_time = process_time()
outputs = list()
for input in inputs:
    try:
        outputs.append([chinese_wall_parking(case) for case in input])
    except TypeError:  # in case input isn't an iterable object
        outputs.append(chinese_wall_parking(input))
end_time = process_time()

judge.verify_output(exercise, outputs, end_time - start_time)
