#!/usr/bin/env python3
import judge
from time import process_time


def func(input):
    """your alorithm"""
    result = list()  # each entry represents one line from the output
    return result


# A&D programming exercise number
exercise = 0
# inputs from the test files
inputs = judge.read_input(exercise)
# outputs generated by the algorithm
start_time = process_time()
outputs = list()
for input in inputs:
    try:
        outputs.append([func(case) for case in input])
    except TypeError:  # in case input isn't an iterable object
        outputs.append(func(input))
end_time = process_time()

judge.verify_output(exercise, outputs, end_time - start_time)
